### ISSUE TITLE
Features ideas

### ISSUE THREAD

**Issue by Tiritibambix** [Casvt/Noted#25]
A couple of functions I've been thinking of.

Maybe they are not hard to implement :

- Possibility to choose week start:  Sunday or Monday
- Possibility to choose between AM/PM and 24h
- Possibility to disable registration
- Possibility to add a color to reminders

**Comment by Casvt** [comment]
Please make seperate requests for each, otherwise I can't manage the project properly.

> Possibility to choose week start: Sunday or Monday

Where in Noted do you encounter something that has to do with the start of the week?

> Possibility to choose between AM/PM and 24h

The time selection you see when adding the reminder is of the browser and is something that I cannot control. If you mean the time shown in the library view, then you got a point and make a request.

> Possibility to disable registration

And instead just a password? Or instead nothing and free access to the UI (because that's dangerous when Noted is port forwarded)?

> Possibility to add a color to reminders

Sure. As I said, make a seperate request for each

**Comment by Tiritibambix** [comment]
> Please make seperate requests for each, otherwise I can't manage the project properly.
> 
> > Possibility to choose week start: Sunday or Monday
> 
> Where in Noted do you encounter something that has to do with the start of the week?
> 
> > Possibility to choose between AM/PM and 24h
> 
> The time selection you see when adding the reminder is of the browser and is something that I cannot control. If you mean the time shown in the library view, then you got a point and make a request.

For both of these, I fixed it by switching my browser's language to French. I'd rather use English, but for the sake of Noted, I can use French.

I'll open new requests for the other points.
