### ISSUE TITLE
Manual Install - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by VlaK0r** [Casvt/Noted#61]
Hello!
Thank you for your work

I can't start the program, it gives an error.

python3 MIND.py
Traceback (most recent call last):
  File "MIND.py", line 15, in <module>
    from frontend.api import api, api_prefix, reminder_handler
  File "/opt/MIND/frontend/api.py", line 21, in <module>
    from backend.notification_service import (NotificationService,
  File "<fstring>", line 1
    (title=)
          ^
SyntaxError: invalid syntax

**Comment by Casvt** [comment]
When I run `python3 MIND.py`, it runs fine. That means that your setup differs from mine in some way that leads to the error. What I find very weird in the traceback that you're supplying is the following:
```
File "", line 1
(title=)
```

Between the quotes, there should be a file listed. On top, there is no file that has `(title=)` at line 1 (like the traceback suggests). There is no file _at all_ that has `(title=)` _anywhere in them_.

-------------------

Because you can run the `MIND.py` file, it seems like `/opt/MIND` has sufficient permissions and ownership. Please check that the following sub-folders also have sufficient permissions and ownership: `backend/`, `db/`, `frontend/`.
