### ISSUE TITLE
Merge conflict committed in v1.4.0

### ISSUE THREAD

**Issue by Dola-Shuvi** [Casvt/Noted#69]
**Description of the bug**
During the merge of #68 a merge conflict has appeared in [general.js](https://github.com/Casvt/MIND/blob/96ead3a6a88e3922cbc317e5b037659bea783827/frontend/static/js/general.js#L67) in the frontend. Upon accessing the MIND admin panel or general user interface, almost none of the buttons have any functionality. In the developer console the following output is found:
`Uncaught SyntaxError: Unexpected token '<<' (at general.js:65:1)`

**To Reproduce**
1. Pull docker image with tag [v1.4.0](https://hub.docker.com/layers/mrcas/mind/v1.4.0/images/sha256-e7ef9176595b5373f4927f07fb7b8534ece6af4f39ed11e782207a735df438a6?context=explore) and start it with the docker-compose from the [installation documentation](https://casvt.github.io/MIND/installation/installation/#__tabbed_1_2).
2. Access the started service in a browser and open the developer tools.
3. Log in to the admin panel with the default admin credentials. Alternatively log in as a user and try to add a reminder.

**Expected behaviour**
I expected MIND to be working without major issues after pulling what I assumed was the latest stable release. I have confirmed version v1.3.3 to be working as expected.

**Version info**
 - OS: Windows 10 22H2 19045.4123
 - Browser: Firefox ESR 115 / Edge 122.0.2365.66
 - MIND Version: v1.4.0
 - Python Version: bundled Docker version

**Additional context**
In addition to the problem listed above, there seems to be an issue in [admin.js](https://github.com/Casvt/MIND/blob/96ead3a6a88e3922cbc317e5b037659bea783827/frontend/static/js/admin.js#L33) where the `api_key` is not defined. Below is the developer tools output:
```
Uncaught ReferenceError: api_key is not defined
    at checkLogin (admin.js:33:49)
    at admin.js:300:1
```

**Comment by Casvt** [comment]
Oh wow I tested it after merging and it worked fine. Don't know how I missed it and why Vs code didn't report it as an error... I'll fix it quickly.

**Comment by Casvt** [comment]
Okay I fixed it all. Just re-download v1.4.0

I was _so_ alert when publishing the new release, making sure that everything was going well, no bugs were pushed and no broken release was published. But then a merge conflict that didn't make sense threw that all off the table and it turned into trying to just get it to merge anyhow. And then mistakes arise of course...

It took me more than an hour of terrible confusion (and out-loud cursing) in order to set everything straight. I don't know what I did, but the programming gods wanted to punish me. And then when trying something that shouldn't work, it worked of course. Now everything seems to be working, I triple checked that the branch was correct and the container would work and the git history of all branches is corrected.

To programming gods: please don't do this ever to me again. I went through 6 beers in 60 minutes out of pure frustration. It's a miracle that my neighbours haven't complained about the noise. I've learned my lesson.

**Comment by Dola-Shuvi** [comment]
No worries about that, these things happen to all of us. I'm glad I managed to help you catch this rather quickly, as today was the first time I found this repo on Github. I can confirm that the latest and v1.4.0 tag now work as intended.

**Comment by LiloBzH** [comment]
Hi !

It doesn't work with "freemobile"

Same error with Key error :

> :40m[21:18:39][ERROR] Unparseable URL freemobile://abc123@98765
> :40m[21:18:39][WARNING] This key in the API request has an invalid value: url = freemobile://abc123@98765
