### ISSUE TITLE
Snooze & NL to add time feature req

### ISSUE THREAD

**Issue by vutsalsinghal** [Casvt/Noted#88]
Hi @Casvt!

Thank you creating MIND.

I had actually created a very basic flask app with form to add reminders and get notified with selfhosted NTFY. But it lacked few features already there in MIND and my app's UI was too plain 😄. 

1. One of the feature I relied on a lot in my app was the ability to snooze. NTFY supports [actions](https://docs.ntfy.sh/publish/#action-buttons) and I could tap the button from the notification to snooze it for 1hr,3hrs, etc (based on my use case). I know not all notifications agents via apprise may support the action functionality but adding support for those that do would be amazing! 🙏🏼 

I can think of 2 ways to achieve snooze
- Maybe user can pass a custom ntfy json with action parameters
- expose MIND api so users can programatically re-add same reminder with updated time

2. There is a python library [dateparser](https://github.com/scrapinghub/dateparser) using which you can use natural language (NL) for date/time input. This will speed up process of adding a reminder on the go. (I use voice input instead of typing on the phone a lot 😆)

**Comment by Casvt** [comment]
Apprise doesn't allow the user to set up these "actions". So it's not happening that way.

So it would need to be implemented by MIND itself. However, unless a reminder is reoccurring (e.g. weekly), it's deleted after it's triggered. That means there's no way to access it afterwards to set the snooze.

Issue #83 will allow you to supply a custom cron schedule for a reminder. This would allow you to kind of replicate a forced snooze, by creating the desired schedule and then altering it so that it also triggers X minutes/hours after the set times.

**Comment by vutsalsinghal** [comment]
Setting snooze via cron doesn't make sense.

is there MIND api to create reminders?

**Comment by Casvt** [comment]
Yeah the documentation hub has the docs: https://casvt.github.io/MIND/other_docs/api/
